// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRfdiGGrzBQ4Ue1mZRGlvozGdUr9cHHF8',
    appId: '1:184549952540:web:e78f07412f3ae02ec723d9',
    messagingSenderId: '184549952540',
    projectId: 'infinity-notes-3101',
    authDomain: 'infinity-notes-3101.firebaseapp.com',
    storageBucket: 'infinity-notes-3101.firebasestorage.app',
    measurementId: 'G-S4YC943MK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApmWjX6lnE8bjfa1dQKbXCgj4K0ZLure4',
    appId: '1:184549952540:android:53593e97045a6f3cc723d9',
    messagingSenderId: '184549952540',
    projectId: 'infinity-notes-3101',
    storageBucket: 'infinity-notes-3101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGpl_4NbyaT02cb3f2g6kS2jGDw3jhOpY',
    appId: '1:184549952540:ios:5cc3b90b2158c292c723d9',
    messagingSenderId: '184549952540',
    projectId: 'infinity-notes-3101',
    storageBucket: 'infinity-notes-3101.firebasestorage.app',
    androidClientId: '184549952540-7veuto0nlvtmmk81uq9b91219n8jncov.apps.googleusercontent.com',
    iosClientId: '184549952540-sjqfds1hst2ubep1m712pprl3tccg6u0.apps.googleusercontent.com',
    iosBundleId: 'com.ehv.infinityNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGpl_4NbyaT02cb3f2g6kS2jGDw3jhOpY',
    appId: '1:184549952540:ios:5cc3b90b2158c292c723d9',
    messagingSenderId: '184549952540',
    projectId: 'infinity-notes-3101',
    storageBucket: 'infinity-notes-3101.firebasestorage.app',
    androidClientId: '184549952540-7veuto0nlvtmmk81uq9b91219n8jncov.apps.googleusercontent.com',
    iosClientId: '184549952540-sjqfds1hst2ubep1m712pprl3tccg6u0.apps.googleusercontent.com',
    iosBundleId: 'com.ehv.infinityNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRfdiGGrzBQ4Ue1mZRGlvozGdUr9cHHF8',
    appId: '1:184549952540:web:f6b8651c6b854672c723d9',
    messagingSenderId: '184549952540',
    projectId: 'infinity-notes-3101',
    authDomain: 'infinity-notes-3101.firebaseapp.com',
    storageBucket: 'infinity-notes-3101.firebasestorage.app',
    measurementId: 'G-ZPJ5V5YVEL',
  );

}